baseurl: ""
include: ['_pages']
excerpt_separator: <!--more-->

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: robf26
